name: Swift

on:
  pull_request:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-13]
        swift: ["5.7.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ☑️ Swift Select
        uses: swift-actions/setup-swift@v1
        with:
            swift-version: ${{ matrix.swift }}

      - name: ⬇️ Get Sources
        uses: actions/checkout@v4.1.2

      - name: 🍀 Test Package
        run: swift test
